version: "3.3"
services:
    jenkins:
        image: jenkinsci/blueocean
        user: root
        container_name: jenkins
        volumes: 
          - /var/run/docker.sock:/var/run/docker.sock
          - jenkins-data:/var/jenkins_home
          - $HOME:/home
        ports:
          - 8080:8080

volumes:
  jenkins-data: 